### ISSUE TITLE
dapple-quicktest does not work now after #155

### ISSUE THREAD

**Issue by r001** [makerdao/maker-otc#158]
$ dapple-quicktest 
MIGRAE: 0.8.37 - add possible missing fields to Dappfile - authors, licence - Apache-2.0, ...
MIGRAE: 0.8.37 - add ./ prefix to layouts in case its missing
/home/geth/npm-global/lib/node_modules/dapple/node_modules/dapple-core/local_migration.js:29
    dappfile.layout = _.mapValues(dappfile.layout, (path, name) => {
                    ^

TypeError: Cannot create property 'layout' on string 'name            maker-otc description     Simple on-chain market for ERC20 tokens version         0.4
author          Nikolai Mushegian <nikolai@nexusdev.us> author          Joris Bontje <jorisbontje@gmail.com> author          Rain <rainbeam@riseup.net> author          Daniel Brockman <daniel@brockman.se> license         Apache-2.0'
    at migrate (/home/geth/npm-global/lib/node_modules/dapple/node_modules/dapple-core/local_migration.js:29:21)
    at migrate (/home/geth/npm-global/lib/node_modules/dapple/node_modules/dapple-core/local_migration.js:15:7)
    at module.exports (/home/geth/npm-global/lib/node_modules/dapple/node_modules/dapple-core/local_migration.js:28:3)
    at async.waterfall (/home/geth/npm-global/lib/node_modules/dapple/node_modules/dapple-core/state.js:56:34)
    at /home/geth/npm-global/lib/node_modules/dapple/node_modules/async/dist/async.js:356:16
    at nextTask (/home/geth/npm-global/lib/node_modules/dapple/node_modules/async/dist/async.js:5057:29)
    at /home/geth/npm-global/lib/node_modules/dapple/node_modules/async/dist/async.js:5064:13
    at apply (/home/geth/npm-global/lib/node_modules/dapple/node_modules/async/dist/async.js:21:25)
    at /home/geth/npm-global/lib/node_modules/dapple/node_modules/async/dist/async.js:56:12
    at /home/geth/npm-global/lib/node_modules/dapple/node_modules/async/dist/async.js:840:16
dapple-quicktest: Error: Command failed: dapple build --test

**Comment by r001** [comment]
I have found the reason for that one. You need to use `make all` instead of `dapple-quicktest` and you also need to run `git submodule update --init --recursive` to download additional dirs from github.
