### ISSUE TITLE
Exception in template helper: BigNumber Error: new BigNumber() not a number

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#44]
When editing one of the input fields and removing the `0` value, the following exception gets thrown:
```
Exception in template helper: BigNumber Error: new BigNumber() not a number: 
    at D (http://makerdao.github.io/maker-otc/319f048bacb37b753c3dd59da85a4ab05e7b23b6.js:82:27055)
    at http://makerdao.github.io/maker-otc/319f048bacb37b753c3dd59da85a4ab05e7b23b6.js:84:615
    at new e (http://makerdao.github.io/maker-otc/319f048bacb37b753c3dd59da85a4ab05e7b23b6.js:82:24979)
    at Object.n (http://makerdao.github.io/maker-otc/319f048bacb37b753c3dd59da85a4ab05e7b23b6.js:160:21322)
    at http://makerdao.github.io/maker-otc/319f048bacb37b753c3dd59da85a4ab05e7b23b6.js:108:30879
    at http://makerdao.github.io/maker-otc/319f048bacb37b753c3dd59da85a4ab05e7b23b6.js:108:16577
    at http://makerdao.github.io/maker-otc/319f048bacb37b753c3dd59da85a4ab05e7b23b6.js:108:31512
    at Function.e._withTemplateInstanceFunc (http://makerdao.github.io/maker-otc/319f048bacb37b753c3dd59da85a4ab05e7b23b6.js:110:5222)
    at http://makerdao.github.io/maker-otc/319f048bacb37b753c3dd59da85a4ab05e7b23b6.js:108:31419
    at s.call (http://makerdao.github.io/maker-otc/319f048bacb37b753c3dd59da85a4ab05e7b23b6.js:112:1929)
```

**Comment by jorisbontje** [comment]
This appears to be solved as side effect of #54
